package com.ujs.spmsys.dao;

import com.ujs.spmsys.entity.Account;
import org.springframework.stereotype.Repository;

@Repository
public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    Account selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int updateByPrimaryKey(Account record);

    Account selectByAccountname(String accountname);
}