package com.ujs.spmsys.dao;

import com.ujs.spmsys.entity.Crossproject;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CrossprojectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Tue May 01 08:51:17 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Tue May 01 08:51:17 CST 2018
     */
    int insert(Crossproject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Tue May 01 08:51:17 CST 2018
     */
    int insertSelective(Crossproject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Tue May 01 08:51:17 CST 2018
     */
    Crossproject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Tue May 01 08:51:17 CST 2018
     */
    int updateByPrimaryKeySelective(Crossproject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Tue May 01 08:51:17 CST 2018
     */
    int updateByPrimaryKey(Crossproject record);

    List<Crossproject> selectByAuthorname(String name);

    Crossproject selectByName(String name);

    List<Crossproject> selectByStatus(Integer status);

    List<Crossproject> selectByType(Integer type);

    List<Crossproject> selectAll();
}