package com.ujs.spmsys.dao;

import com.ujs.spmsys.entity.Crossproject;

public interface CrossprojectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int insert(Crossproject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int insertSelective(Crossproject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    Crossproject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int updateByPrimaryKeySelective(Crossproject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int updateByPrimaryKey(Crossproject record);
}