package com.ujs.spmsys.dao;

import com.ujs.spmsys.entity.Crosappform;

public interface CrosappformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crosappform
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int deleteByPrimaryKey(Integer projectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crosappform
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int insert(Crosappform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crosappform
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int insertSelective(Crosappform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crosappform
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    Crosappform selectByPrimaryKey(Integer projectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crosappform
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int updateByPrimaryKeySelective(Crosappform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crosappform
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int updateByPrimaryKey(Crosappform record);
}