package com.ujs.spmsys.dao;

import com.ujs.spmsys.entity.Crossproject;
import org.springframework.stereotype.Repository;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.List;

@Repository
public interface CrossprojectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    int insert(Crossproject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    int insertSelective(Crossproject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    Crossproject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    int updateByPrimaryKeySelective(Crossproject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossproject
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    int updateByPrimaryKey(Crossproject record);

    List<Crossproject> selectByAuthorname(String name);
}