package com.ujs.spmsys.dao;

import com.ujs.spmsys.entity.Crossappfile;
import org.springframework.stereotype.Repository;

@Repository
public interface CrossappfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossappfile
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossappfile
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    int insert(Crossappfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossappfile
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    int insertSelective(Crossappfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossappfile
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    Crossappfile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossappfile
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    int updateByPrimaryKeySelective(Crossappfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crossappfile
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    int updateByPrimaryKey(Crossappfile record);
}