package com.ujs.spmsys.dao;

import com.ujs.spmsys.entity.File;

public interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    int insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    int insertSelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    File selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    int updateByPrimaryKeySelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    int updateByPrimaryKey(File record);
}