package com.ujs.spmsys.dao;

import com.ujs.spmsys.entity.Userinfo;
import org.springframework.stereotype.Repository;

@Repository
public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int deleteByPrimaryKey(Integer accountid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int insertSelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    Userinfo selectByPrimaryKey(Integer accountid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int updateByPrimaryKeySelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    int updateByPrimaryKey(Userinfo record);
}