package com.ujs.spmsys.dao;

import com.ujs.spmsys.entity.Userinfo;

public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    int deleteByPrimaryKey(Integer accountid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    int insertSelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    Userinfo selectByPrimaryKey(Integer accountid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    int updateByPrimaryKeySelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    int updateByPrimaryKey(Userinfo record);
}