package com.ujs.spmsys.entity;

public class AppMaterial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_material.id
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_material.title
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_material.path
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_material.reid
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private Integer reid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_material.id
     *
     * @return the value of app_material.id
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_material.id
     *
     * @param id the value for app_material.id
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_material.title
     *
     * @return the value of app_material.title
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_material.title
     *
     * @param title the value for app_material.title
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_material.path
     *
     * @return the value of app_material.path
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_material.path
     *
     * @param path the value for app_material.path
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_material.reid
     *
     * @return the value of app_material.reid
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public Integer getReid() {
        return reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_material.reid
     *
     * @param reid the value for app_material.reid
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setReid(Integer reid) {
        this.reid = reid;
    }
}