package com.ujs.spmsys.entity;

import java.util.Date;

public class Crossappfile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crossappfile.id
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crossappfile.filepath
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    private String filepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crossappfile.uptime
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    private Date uptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crossappfile.filename
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    private String filename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crossappfile.id
     *
     * @return the value of crossappfile.id
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crossappfile.id
     *
     * @param id the value for crossappfile.id
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crossappfile.filepath
     *
     * @return the value of crossappfile.filepath
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crossappfile.filepath
     *
     * @param filepath the value for crossappfile.filepath
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crossappfile.uptime
     *
     * @return the value of crossappfile.uptime
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    public Date getUptime() {
        return uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crossappfile.uptime
     *
     * @param uptime the value for crossappfile.uptime
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    public void setUptime(Date uptime) {
        this.uptime = uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crossappfile.filename
     *
     * @return the value of crossappfile.filename
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crossappfile.filename
     *
     * @param filename the value for crossappfile.filename
     *
     * @mbg.generated Thu Apr 26 15:53:15 CST 2018
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }
}