package com.ujs.spmsys.entity;

import java.util.Date;

public class Crossproject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crossproject.id
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crossproject.name
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crossproject.authorname
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    private String authorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crossproject.apptime
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    private Date apptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crossproject.status
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crossproject.id
     *
     * @return the value of crossproject.id
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crossproject.id
     *
     * @param id the value for crossproject.id
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crossproject.name
     *
     * @return the value of crossproject.name
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crossproject.name
     *
     * @param name the value for crossproject.name
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crossproject.authorname
     *
     * @return the value of crossproject.authorname
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    public String getAuthorname() {
        return authorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crossproject.authorname
     *
     * @param authorname the value for crossproject.authorname
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    public void setAuthorname(String authorname) {
        this.authorname = authorname == null ? null : authorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crossproject.apptime
     *
     * @return the value of crossproject.apptime
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    public Date getApptime() {
        return apptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crossproject.apptime
     *
     * @param apptime the value for crossproject.apptime
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    public void setApptime(Date apptime) {
        this.apptime = apptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crossproject.status
     *
     * @return the value of crossproject.status
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crossproject.status
     *
     * @param status the value for crossproject.status
     *
     * @mbg.generated Thu Apr 19 15:26:33 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}