package com.ujs.spmsys.entity;

import java.util.Date;

public class Crosappform {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crosappform.projectid
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private Integer projectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crosappform.name
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crosappform.type
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crosappform.research_cost
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private Integer researchCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crosappform.expected_founds
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private Integer expectedFounds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crosappform.expected_finish_time
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private Date expectedFinishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crosappform.partner
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private String partner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crosappform.applicant
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private Integer applicant;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crosappform.projectid
     *
     * @return the value of crosappform.projectid
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crosappform.projectid
     *
     * @param projectid the value for crosappform.projectid
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crosappform.name
     *
     * @return the value of crosappform.name
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crosappform.name
     *
     * @param name the value for crosappform.name
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crosappform.type
     *
     * @return the value of crosappform.type
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crosappform.type
     *
     * @param type the value for crosappform.type
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crosappform.research_cost
     *
     * @return the value of crosappform.research_cost
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public Integer getResearchCost() {
        return researchCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crosappform.research_cost
     *
     * @param researchCost the value for crosappform.research_cost
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setResearchCost(Integer researchCost) {
        this.researchCost = researchCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crosappform.expected_founds
     *
     * @return the value of crosappform.expected_founds
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public Integer getExpectedFounds() {
        return expectedFounds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crosappform.expected_founds
     *
     * @param expectedFounds the value for crosappform.expected_founds
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setExpectedFounds(Integer expectedFounds) {
        this.expectedFounds = expectedFounds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crosappform.expected_finish_time
     *
     * @return the value of crosappform.expected_finish_time
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public Date getExpectedFinishTime() {
        return expectedFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crosappform.expected_finish_time
     *
     * @param expectedFinishTime the value for crosappform.expected_finish_time
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setExpectedFinishTime(Date expectedFinishTime) {
        this.expectedFinishTime = expectedFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crosappform.partner
     *
     * @return the value of crosappform.partner
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public String getPartner() {
        return partner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crosappform.partner
     *
     * @param partner the value for crosappform.partner
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setPartner(String partner) {
        this.partner = partner == null ? null : partner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crosappform.applicant
     *
     * @return the value of crosappform.applicant
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public Integer getApplicant() {
        return applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crosappform.applicant
     *
     * @param applicant the value for crosappform.applicant
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setApplicant(Integer applicant) {
        this.applicant = applicant;
    }
}