package com.ujs.spmsys.entity;

public class Crossproject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crossproject.id
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crossproject.status
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crossproject.id
     *
     * @return the value of crossproject.id
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crossproject.id
     *
     * @param id the value for crossproject.id
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crossproject.status
     *
     * @return the value of crossproject.status
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crossproject.status
     *
     * @param status the value for crossproject.status
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}