package com.ujs.spmsys.entity;

public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbg.generated Thu Apr 26 22:29:56 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.type
     *
     * @mbg.generated Thu Apr 26 22:29:56 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.name
     *
     * @mbg.generated Thu Apr 26 22:29:56 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.filepath
     *
     * @mbg.generated Thu Apr 26 22:29:56 CST 2018
     */
    private String filepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.accountid
     *
     * @mbg.generated Thu Apr 26 22:29:56 CST 2018
     */
    private Integer accountid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbg.generated Thu Apr 26 22:29:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbg.generated Thu Apr 26 22:29:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.type
     *
     * @return the value of item.type
     *
     * @mbg.generated Thu Apr 26 22:29:56 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.type
     *
     * @param type the value for item.type
     *
     * @mbg.generated Thu Apr 26 22:29:56 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.name
     *
     * @return the value of item.name
     *
     * @mbg.generated Thu Apr 26 22:29:56 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.name
     *
     * @param name the value for item.name
     *
     * @mbg.generated Thu Apr 26 22:29:56 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.filepath
     *
     * @return the value of item.filepath
     *
     * @mbg.generated Thu Apr 26 22:29:56 CST 2018
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.filepath
     *
     * @param filepath the value for item.filepath
     *
     * @mbg.generated Thu Apr 26 22:29:56 CST 2018
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.accountid
     *
     * @return the value of item.accountid
     *
     * @mbg.generated Thu Apr 26 22:29:56 CST 2018
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.accountid
     *
     * @param accountid the value for item.accountid
     *
     * @mbg.generated Thu Apr 26 22:29:56 CST 2018
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }
}