package com.ujs.spmsys.entity;

import java.util.Date;

public class Reseacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reseacher.id
     *
     * @mbg.generated Sun Apr 01 13:09:58 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reseacher.name
     *
     * @mbg.generated Sun Apr 01 13:09:58 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reseacher.passwd
     *
     * @mbg.generated Sun Apr 01 13:09:58 CST 2018
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reseacher.regtime
     *
     * @mbg.generated Sun Apr 01 13:09:58 CST 2018
     */
    private Date regtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reseacher.id
     *
     * @return the value of reseacher.id
     *
     * @mbg.generated Sun Apr 01 13:09:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reseacher.id
     *
     * @param id the value for reseacher.id
     *
     * @mbg.generated Sun Apr 01 13:09:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reseacher.name
     *
     * @return the value of reseacher.name
     *
     * @mbg.generated Sun Apr 01 13:09:58 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reseacher.name
     *
     * @param name the value for reseacher.name
     *
     * @mbg.generated Sun Apr 01 13:09:58 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reseacher.passwd
     *
     * @return the value of reseacher.passwd
     *
     * @mbg.generated Sun Apr 01 13:09:58 CST 2018
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reseacher.passwd
     *
     * @param passwd the value for reseacher.passwd
     *
     * @mbg.generated Sun Apr 01 13:09:58 CST 2018
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reseacher.regtime
     *
     * @return the value of reseacher.regtime
     *
     * @mbg.generated Sun Apr 01 13:09:58 CST 2018
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reseacher.regtime
     *
     * @param regtime the value for reseacher.regtime
     *
     * @mbg.generated Sun Apr 01 13:09:58 CST 2018
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
}