package com.ujs.spmsys.entity;

import java.util.Date;

public class Researcher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column researcher.id
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column researcher.name
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column researcher.passwd
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column researcher.regtime
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    private Date regtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column researcher.id
     *
     * @return the value of researcher.id
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column researcher.id
     *
     * @param id the value for researcher.id
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column researcher.name
     *
     * @return the value of researcher.name
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column researcher.name
     *
     * @param name the value for researcher.name
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column researcher.passwd
     *
     * @return the value of researcher.passwd
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column researcher.passwd
     *
     * @param passwd the value for researcher.passwd
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column researcher.regtime
     *
     * @return the value of researcher.regtime
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column researcher.regtime
     *
     * @param regtime the value for researcher.regtime
     *
     * @mbg.generated Mon Apr 02 10:35:35 CST 2018
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
}