package com.ujs.spmsys.entity;

import java.util.Date;

public class Userinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.accountid
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private Integer accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.name
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.birthday
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.job
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.staffnum
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private Integer staffnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.email
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.address
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.accounttype
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    private String accounttype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.accountid
     *
     * @return the value of userinfo.accountid
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.accountid
     *
     * @param accountid the value for userinfo.accountid
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.name
     *
     * @return the value of userinfo.name
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.name
     *
     * @param name the value for userinfo.name
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.birthday
     *
     * @return the value of userinfo.birthday
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.birthday
     *
     * @param birthday the value for userinfo.birthday
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.job
     *
     * @return the value of userinfo.job
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.job
     *
     * @param job the value for userinfo.job
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.staffnum
     *
     * @return the value of userinfo.staffnum
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public Integer getStaffnum() {
        return staffnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.staffnum
     *
     * @param staffnum the value for userinfo.staffnum
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setStaffnum(Integer staffnum) {
        this.staffnum = staffnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.email
     *
     * @return the value of userinfo.email
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.email
     *
     * @param email the value for userinfo.email
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.address
     *
     * @return the value of userinfo.address
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.address
     *
     * @param address the value for userinfo.address
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.accounttype
     *
     * @return the value of userinfo.accounttype
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public String getAccounttype() {
        return accounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.accounttype
     *
     * @param accounttype the value for userinfo.accounttype
     *
     * @mbg.generated Sun Apr 15 09:52:52 CST 2018
     */
    public void setAccounttype(String accounttype) {
        this.accounttype = accounttype == null ? null : accounttype.trim();
    }
}