package com.ujs.spmsys.entity;

import java.util.Date;

public class Userinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.accountid
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    private Integer accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.name
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.staffnum
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    private String staffnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.birthday
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.tel
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.email
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.job
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.office
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    private String office;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.specialization
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    private String specialization;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.address
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.accounttype
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    private String accounttype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.accountid
     *
     * @return the value of userinfo.accountid
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.accountid
     *
     * @param accountid the value for userinfo.accountid
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.name
     *
     * @return the value of userinfo.name
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.name
     *
     * @param name the value for userinfo.name
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.staffnum
     *
     * @return the value of userinfo.staffnum
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public String getStaffnum() {
        return staffnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.staffnum
     *
     * @param staffnum the value for userinfo.staffnum
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public void setStaffnum(String staffnum) {
        this.staffnum = staffnum == null ? null : staffnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.birthday
     *
     * @return the value of userinfo.birthday
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.birthday
     *
     * @param birthday the value for userinfo.birthday
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.tel
     *
     * @return the value of userinfo.tel
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.tel
     *
     * @param tel the value for userinfo.tel
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.email
     *
     * @return the value of userinfo.email
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.email
     *
     * @param email the value for userinfo.email
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.job
     *
     * @return the value of userinfo.job
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.job
     *
     * @param job the value for userinfo.job
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.office
     *
     * @return the value of userinfo.office
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public String getOffice() {
        return office;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.office
     *
     * @param office the value for userinfo.office
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public void setOffice(String office) {
        this.office = office == null ? null : office.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.specialization
     *
     * @return the value of userinfo.specialization
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public String getSpecialization() {
        return specialization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.specialization
     *
     * @param specialization the value for userinfo.specialization
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public void setSpecialization(String specialization) {
        this.specialization = specialization == null ? null : specialization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.address
     *
     * @return the value of userinfo.address
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.address
     *
     * @param address the value for userinfo.address
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.accounttype
     *
     * @return the value of userinfo.accounttype
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public String getAccounttype() {
        return accounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.accounttype
     *
     * @param accounttype the value for userinfo.accounttype
     *
     * @mbg.generated Sat Apr 21 20:52:14 CST 2018
     */
    public void setAccounttype(String accounttype) {
        this.accounttype = accounttype == null ? null : accounttype.trim();
    }
}